name: "ACPR 2019 Organising Committee"
author: "ACPR 2019 Organising Committee"
baseurl: https://andrewchenuoa.github.io/ACPR2019
description: "5th Asian Conference on Pattern Recognition"

##Make sure to edit the above fields, especially for disqus.

highlighter: rouge
markdown: redcarpet
redcarpet:
  extensions: ["tables"]

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
